import 'dart:async';
import 'dart:math';

import 'package:firebase_auth/firebase_auth.dart' as fb;
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

import '../l10n/generated/app_localizations.dart';
import '../mock_data.dart';
import '../models/models.dart';
import '../services/auth_service.dart';
import '../services/email_service.dart';
import '../services/telemetry_server.dart';
import '../services/tts_service.dart';

class AppState extends ChangeNotifier {
  // ---- Auth ---------------------------------------------------------------
  UserAccount? currentUser;
  bool authLoading = true; // true while we check for an existing Firebase session
  String? authError;
  StreamSubscription<fb.User?>? _authSub;

  // ---- Localization & accessibility -----------------------------------------
  Locale locale = const Locale('en');
  final TtsService tts = TtsService();
  bool get ttsEnabled => tts.enabled;

  /// Switches the app's display language AND the TTS voice together, so
  /// they never drift out of sync (e.g. English text with a Kannada
  /// voice reading it).
  void setLocale(Locale newLocale) {
    locale = newLocale;
    tts.setLanguage(newLocale.languageCode);
    notifyListeners();
  }

  void toggleTts() {
    tts.enabled = !tts.enabled;
    if (!tts.enabled) tts.stop();
    notifyListeners();
  }

  /// `lookupAppLocalizations` is generated by the l10n codegen and, unlike
  /// `AppLocalizations.of(context)`, doesn't need a BuildContext — which is
  /// exactly what we need here since AppState has no widget tree access.
  /// This is what lets a background event (a hardware RFID tap, a
  /// simulator tick) speak in whichever language the user last picked.
  AppLocalizations get _l10n => lookupAppLocalizations(locale);

  AppState() {
    telemetryServer = TelemetryServer(
      onTap: _handleHardwareTap,
      onHardwareEvent: _handleHardwareEvent,
      onStopUpdate: _handleStopUpdate,
    );
    _authSub = AuthService.authStateChanges.listen(_onFirebaseUserChanged);
    TelemetryServer.localIpAddresses().then((ips) {
      localIps = ips;
      notifyListeners();
    });
    tts.setLanguage(locale.languageCode);
    // Start listening for ESP32 taps immediately — previously this only
    // started when "Start Simulator" was pressed, which was a common
    // source of "the ESP32 can't connect" confusion during setup/testing.
    startTelemetryServer();
  }

  Future<void> _onFirebaseUserChanged(fb.User? firebaseUser) async {
    if (firebaseUser == null) {
      currentUser = null;
      authLoading = false;
      notifyListeners();
      return;
    }
    final profile = await AuthService.loadProfileForCurrentUser();
    currentUser = profile;
    authLoading = false;
    notifyListeners();
  }

  // ---- Route / simulator ---------------------------------------------------
  final List<RouteStop> stops = kRouteStops;
  int currentStopIndex = 0;
  bool simulatorRunning = false;
  double speedKmh = 0;
  Timer? _simTimer;
  double routeProgress = 0; // 0..1 between currentStopIndex and next

  // ---- Fleet metrics --------------------------------------------------------
  int onboardCount = 0;
  int enteredCount = 0;
  int exitedCount = 0;
  static const int busCapacity = 40;

  // ---- RFID wallets & feed --------------------------------------------------
  final List<RfidWallet> wallets = buildInitialWallets();
  final List<FareTransaction> transactions = [];

  // ---- Telemetry / ESP32 link -----------------------------------------------
  TelemetryStatus telemetry = const TelemetryStatus();
  String esp32Ip = ''; // e.g. 192.168.1.42 — set from the settings field
  late final TelemetryServer telemetryServer;
  int serverPort = 8080;

  // ---- SMS-style slide banners -----------------------------------------------
  final List<String> _bannerQueue = [];
  String? activeBanner;

  RouteStop get currentStop => stops[currentStopIndex];
  RouteStop get nextStop => stops[min(currentStopIndex + 1, stops.length - 1)];

  // ============================ AUTH ========================================
  /// Real Firebase sign-in. Returns true on success; on failure sets
  /// authError to a readable message and returns false.
  Future<bool> login(String email, String password) async {
    authError = null;
    try {
      final profile = await AuthService.signIn(email: email, password: password);
      currentUser = profile;
      notifyListeners();

      // Send the real "you just logged in" email and surface the outcome —
      // a silent failure here is exactly the "emails not arriving, why?"
      // confusion the setup guide warns about, so we tell the person
      // immediately instead of only logging to the console.
      unawaited(_sendLoginEmailAndReport(profile));
      return true;
    } on fb.FirebaseAuthException catch (e) {
      authError = _readableAuthError(e.code);
      notifyListeners();
      return false;
    }
  }

  Future<bool> registerPassenger({
    required String email,
    required String password,
    required String username,
    required String linkedUid,
  }) async {
    authError = null;
    try {
      final profile = await AuthService.registerPassenger(
        email: email,
        password: password,
        username: username,
        linkedUid: linkedUid,
      );
      currentUser = profile;
      notifyListeners();
      unawaited(_sendLoginEmailAndReport(profile));
      return true;
    } on fb.FirebaseAuthException catch (e) {
      authError = _readableAuthError(e.code);
      notifyListeners();
      return false;
    }
  }

  String _readableAuthError(String code) {
    switch (code) {
      case 'user-not-found':
        return 'No account found for that email.';
      case 'wrong-password':
      case 'invalid-credential':
        return 'Incorrect email or password.';
      case 'email-already-in-use':
        return 'That email is already registered — try logging in instead.';
      case 'weak-password':
        return 'Password must be at least 6 characters.';
      case 'invalid-email':
        return 'That email address looks invalid.';
      case 'no-profile':
        return 'This account has no role assigned yet. Ask the admin to set one up in Firestore.';
      default:
        return 'Authentication error ($code).';
    }
  }

  Future<void> _sendLoginEmailAndReport(UserAccount profile) async {
    final result = await EmailService.sendLoginNotification(
      toEmail: profile.email,
      username: profile.username,
      role: profile.role == UserRole.admin ? 'Admin / Operator' : 'Passenger',
    );
    if (result.sent) {
      _pushBanner('📧 Login confirmation emailed to ${profile.email}.');
    } else {
      _pushBanner('⚠️ ${result.reason}');
    }
  }

  void logout() {
    AuthService.signOut();
  }

  // ============================ TELEMETRY SERVER =============================
  List<String> localIps = [];

  Future<void> startTelemetryServer() async {
    final boundPort = await telemetryServer.start(port: serverPort);
    if (boundPort != null) {
      serverPort = boundPort;
    }
    localIps = await TelemetryServer.localIpAddresses();
    notifyListeners();
  }

  /// Called synchronously by TelemetryServer whenever the ESP32 posts a tap.
  /// Must return the JSON map that gets sent straight back to the board.
  Map<String, dynamic> _handleHardwareTap(String uid) {
    telemetry = telemetry.copyWith(esp32Connected: true, lastPing: DateTime.now());
    final result = _processTap(uid, source: 'ESP32');
    notifyListeners();
    return result;
  }

  /// For self-contained hardware (your Arduino/ESP32 sketch, which keeps
  /// its own card database and decides fares itself) — this only DISPLAYS
  /// what already happened on the board. It never touches `wallets` or
  /// deducts any balance here, so there is no double-deduction between
  /// your hardware's own balances and this app's separate demo wallets.
  ///
  /// Expected payload: {"uid","name","type":"ENTRY"|"EXIT"|"DENIED_INVALID"
  /// |"DENIED_BALANCE","stop","fare","balance"}
  void _handleHardwareEvent(Map<String, dynamic> data) {
    telemetry = telemetry.copyWith(esp32Connected: true, lastPing: DateTime.now());

    final uid = (data['uid'] ?? '').toString().toUpperCase();
    final name = (data['name'] ?? 'Unknown').toString();
    final type = (data['type'] ?? '').toString();
    final stop = (data['stop'] ?? currentStop.name).toString();
    final fare = (data['fare'] as num?)?.toDouble() ?? 0;
    final balance = (data['balance'] as num?)?.toDouble() ?? 0;

    switch (type) {
      case 'ENTRY':
        onboardCount++;
        enteredCount++;
        _addTransaction(FareTransaction(
          time: DateTime.now(), uid: uid, holder: name, type: TxType.boarding,
          stop: stop, amount: -fare, balanceAfter: balance,
        ));
        _pushBanner('SMS Alert: ₹${fare.toStringAsFixed(2)} debited from Smart Card (UID: $uid) '
            'at $stop. Current Balance: ₹${balance.toStringAsFixed(2)}.');
        tts.speak(_l10n.ttsBoarding(name, stop, fare.toStringAsFixed(0)));
        break;
      case 'EXIT':
        onboardCount = max(0, onboardCount - 1);
        exitedCount++;
        _addTransaction(FareTransaction(
          time: DateTime.now(), uid: uid, holder: name, type: TxType.exit,
          stop: stop, amount: -fare, balanceAfter: balance,
        ));
        _pushBanner('SMS Alert: ${name} tapped out (Exit) at $stop. '
            'Fare ₹${fare.toStringAsFixed(2)} deducted. Current Balance: ₹${balance.toStringAsFixed(2)}.');
        tts.speak(_l10n.ttsExit(name, stop));
        break;
      case 'DENIED_INVALID':
      case 'DENIED_BALANCE':
        _pushBanner('SMS Alert: Access DENIED at $stop (${type == 'DENIED_INVALID' ? 'unregistered card' : 'insufficient balance'}).');
        tts.speak(_l10n.ttsDenied);
        break;
    }
    notifyListeners();
  }

  /// The physical bus reporting its current stop (from the Arduino/ESP32's
  /// START/STOP buttons) — updates the dashboard's "Current Stop" and live
  /// map to track the REAL bus instead of only the on-screen simulator.
  /// Expected payload: {"stopNum": 3, "stopName": "KR Circle", "moving": true}
  void _handleStopUpdate(Map<String, dynamic> data) {
    telemetry = telemetry.copyWith(esp32Connected: true, lastPing: DateTime.now());
    final stopNum = (data['stopNum'] as num?)?.toInt();
    final moving = data['moving'] as bool?;

    if (stopNum != null && stopNum >= 1 && stopNum <= stops.length) {
      currentStopIndex = stopNum - 1; // hardware stops are 1-indexed, list is 0-indexed
      routeProgress = 0;
    }
    if (moving != null) {
      simulatorRunning = moving; // reuses the same "MOVING"/"STOPPED" status card
      speedKmh = moving ? speedKmh.clamp(18, 40).toDouble() : 0;
    }
    notifyListeners();
  }

  /// Also used by the on-screen "Simulate Tap" debug control, so you can
  /// demo the whole flow without physical hardware connected.
  Map<String, dynamic> simulateTap(String uid) {
    final result = _processTap(uid, source: 'Simulator');
    notifyListeners();
    return result;
  }

  Map<String, dynamic> _processTap(String uid, {required String source}) {
    final idx = wallets.indexWhere((w) => w.uid == uid);
    if (idx == -1) {
      _pushBanner('SMS Alert: Unregistered card ($uid) tapped at ${currentStop.name}. Access DENIED.');
      tts.speak(_l10n.ttsDenied);
      return {'status': 'DENIED', 'reason': 'unregistered'};
    }
    final wallet = wallets[idx];

    if (!wallet.onboard) {
      // ---- BOARDING ----
      final fare = currentStop.fare == 0 ? 15.0 : currentStop.fare;
      if (wallet.balance < fare) {
        _pushBanner('SMS Alert: Insufficient balance on ${wallet.holderName}\'s card (UID: $uid). '
            'Balance: ₹${wallet.balance.toStringAsFixed(2)}. Access DENIED.');
        tts.speak(_l10n.ttsDenied);
        return {'status': 'DENIED', 'reason': 'insufficient_balance', 'balance': wallet.balance};
      }
      wallet.balance -= fare;
      wallet.onboard = true;
      onboardCount++;
      enteredCount++;
      _addTransaction(FareTransaction(
        time: DateTime.now(),
        uid: uid,
        holder: wallet.holderName,
        type: TxType.boarding,
        stop: currentStop.name,
        amount: -fare,
        balanceAfter: wallet.balance,
      ));
      _pushBanner('SMS Alert: ₹${fare.toStringAsFixed(2)} debited from Smart Card (UID: $uid) '
          'at ${currentStop.name}. Current Balance: ₹${wallet.balance.toStringAsFixed(2)}.');
      tts.speak(_l10n.ttsBoarding(wallet.holderName, currentStop.name, fare.toStringAsFixed(0)));
      return {'status': 'APPROVED', 'balance': wallet.balance, 'type': 'BOARDING', 'audio': currentStop.audioTrack};
    } else {
      // ---- EXIT ----
      wallet.onboard = false;
      onboardCount = max(0, onboardCount - 1);
      exitedCount++;
      _addTransaction(FareTransaction(
        time: DateTime.now(),
        uid: uid,
        holder: wallet.holderName,
        type: TxType.exit,
        stop: currentStop.name,
        amount: 0,
        balanceAfter: wallet.balance,
      ));
      _pushBanner('SMS Alert: ${wallet.holderName} tapped out (Exit) at ${currentStop.name}. '
          'Current Balance: ₹${wallet.balance.toStringAsFixed(2)}.');
      tts.speak(_l10n.ttsExit(wallet.holderName, currentStop.name));
      return {'status': 'APPROVED', 'balance': wallet.balance, 'type': 'EXIT', 'audio': currentStop.audioTrack};
    }
  }

  // ============================ RECHARGE ======================================
  Future<void> recharge(String uid, double amount) async {
    final idx = wallets.indexWhere((w) => w.uid == uid);
    if (idx == -1) return;
    final wallet = wallets[idx];
    wallet.balance += amount;

    _addTransaction(FareTransaction(
      time: DateTime.now(),
      uid: uid,
      holder: wallet.holderName,
      type: TxType.recharge,
      stop: '-',
      amount: amount,
      balanceAfter: wallet.balance,
    ));
    _pushBanner('SMS Alert: +₹${amount.toStringAsFixed(2)} RECHARGE successful on Smart Card (UID: $uid). '
        'Current Balance: ₹${wallet.balance.toStringAsFixed(2)}.');
    tts.speak(_l10n.ttsRecharge(wallet.balance.toStringAsFixed(0)));

    notifyListeners();

    // Push the new balance down to the ESP32's local memory if we know its IP.
    if (esp32Ip.isNotEmpty) {
      try {
        await http.post(
          Uri.parse('http://$esp32Ip/recharge'),
          headers: {'content-type': 'application/json'},
          body: '{"uid":"$uid","balance":${wallet.balance}}',
        );
      } catch (_) {
        // Board offline / wrong IP — recharge already applied locally, ignore.
      }
    }
  }

  void addWallet(String uid, String name) {
    if (wallets.any((w) => w.uid == uid)) return;
    wallets.add(RfidWallet(uid: uid.toUpperCase(), holderName: name, balance: 0));
    notifyListeners();
  }

  // ============================ SIMULATOR =====================================
  void startSimulator() {
    if (simulatorRunning) return;
    simulatorRunning = true;
    speedKmh = 24 + Random().nextInt(12).toDouble();
    _simTimer = Timer.periodic(const Duration(seconds: 4), (_) {
      routeProgress += 0.25;
      speedKmh = 18 + Random().nextInt(20).toDouble();
      if (routeProgress >= 1.0) {
        routeProgress = 0;
        if (currentStopIndex < stops.length - 1) {
          currentStopIndex++;
        } else {
          currentStopIndex = 0; // loop the route for the demo
        }
        // IoT-data-driven TTS: this fires purely off the simulated GPS/stop
        // update, exactly like it would off a real ESP32 GPS ping — "Bus
        // reaching stop 25A" style announcement, in whichever language the
        // rider/operator has selected.
        tts.speak(_l10n.ttsApproachingStop(currentStop.name));
      }
      notifyListeners();
    });
    notifyListeners();
  }

  void stopSimulator() {
    simulatorRunning = false;
    speedKmh = 0;
    _simTimer?.cancel();
    notifyListeners();
  }

  // ============================ BANNERS =======================================
  void _pushBanner(String text) {
    _bannerQueue.add(text);
    _drainBannerQueue();
  }

  void _drainBannerQueue() {
    if (activeBanner != null || _bannerQueue.isEmpty) return;
    activeBanner = _bannerQueue.removeAt(0);
    notifyListeners();
    Timer(const Duration(seconds: 4), () {
      activeBanner = null;
      notifyListeners();
      _drainBannerQueue();
    });
  }

  void _addTransaction(FareTransaction tx) {
    transactions.insert(0, tx);
    if (transactions.length > 200) transactions.removeLast();
  }

  @override
  void dispose() {
    _simTimer?.cancel();
    _authSub?.cancel();
    telemetryServer.stop();
    tts.dispose();
    super.dispose();
  }
}
