// GENERATED PLACEHOLDER — DO NOT EDIT BY HAND.
//
// This file is normally auto-generated by running:
//
//     flutterfire configure
//
// from the project root (see SETUP_GUIDE.md, section 6). That command
// talks to your Firebase project and overwrites this file with your real
// apiKey / appId / projectId values for each platform you select
// (Android / iOS / web). Until you run it, Firebase.initializeApp() in
// main.dart will fail with a clear "no options for this platform" error —
// that's expected and just means this step hasn't been done yet.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Run `flutterfire configure` to generate real web options before using web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform. '
          'Run `flutterfire configure` to add it.',
        );
    }
  }

  // Placeholder values — flutterfire configure overwrites these.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME',
    iosBundleId: 'REPLACE_ME',
  );
}
